"""init schema

Revision ID: 2e68f1557ac8
Revises: 
Create Date: 2026-05-09 01:23:10.287501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e68f1557ac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('PHOTO', 'VOICE', 'MESSAGE', 'STORYBOOK', 'PERSONA', 'CHAT', name='deletionitemtype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='deletionstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_paths', sa.String(length=2048), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_id'), 'deletion_requests', ['id'], unique=False)
    op.create_index(op.f('ix_deletion_requests_user_id'), 'deletion_requests', ['user_id'], unique=False)
    op.create_table('memory_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('invite_link_token', sa.String(length=64), nullable=True),
    sa.Column('profile_image_path', sa.String(length=512), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_link_token')
    )
    op.create_index(op.f('ix_memory_groups_creator_id'), 'memory_groups', ['creator_id'], unique=False)
    op.create_index(op.f('ix_memory_groups_group_code'), 'memory_groups', ['group_code'], unique=True)
    op.create_index(op.f('ix_memory_groups_id'), 'memory_groups', ['id'], unique=False)
    op.create_table('photo_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_file_path', sa.String(length=512), nullable=False),
    sa.Column('photo_mime_type', sa.String(length=100), nullable=False),
    sa.Column('photo_original_filename', sa.String(length=512), nullable=False),
    sa.Column('photo_description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_memories_id'), 'photo_memories', ['id'], unique=False)
    op.create_index(op.f('ix_photo_memories_user_id'), 'photo_memories', ['user_id'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_type', sa.Enum('PARENT', 'GRANDPARENT', 'FRIEND', 'ROMANTIC', 'SELF', 'OTHER', name='targettype'), nullable=False),
    sa.Column('profile_image_path', sa.String(length=512), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_index(op.f('ix_targets_user_id'), 'targets', ['user_id'], unique=False)
    op.create_table('ai_interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('photo_memory_id', sa.Integer(), nullable=True),
    sa.Column('interview_type', sa.Enum('TARGET_PROFILE', 'PHOTO_MEMORY', 'PERSONA_CREATION', name='interviewtype'), nullable=False),
    sa.Column('current_question', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('follow_up_question', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_memory_id'], ['photo_memories.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interview_sessions_id'), 'ai_interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interview_sessions_photo_memory_id'), 'ai_interview_sessions', ['photo_memory_id'], unique=False)
    op.create_index(op.f('ix_ai_interview_sessions_target_id'), 'ai_interview_sessions', ['target_id'], unique=False)
    op.create_index(op.f('ix_ai_interview_sessions_user_id'), 'ai_interview_sessions', ['user_id'], unique=False)
    op.create_table('consent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('consent_type', sa.Enum('VOICE_COLLECTION', 'PHOTO_COLLECTION', 'PERSONA_CREATION', 'DATA_USAGE', 'AI_PROCESSING', name='consenttype'), nullable=False),
    sa.Column('is_consented', sa.Boolean(), nullable=False),
    sa.Column('details', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_logs_id'), 'consent_logs', ['id'], unique=False)
    op.create_index(op.f('ix_consent_logs_target_id'), 'consent_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_consent_logs_user_id'), 'consent_logs', ['user_id'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'COMMENT', 'EDIT', name='sharepermission'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['memory_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATING', 'ACTIVE', 'INACTIVE', name='personastatus'), nullable=False),
    sa.Column('personality_summary', sa.Text(), nullable=True),
    sa.Column('speaking_style', sa.Text(), nullable=True),
    sa.Column('values_beliefs', sa.Text(), nullable=True),
    sa.Column('memorable_episodes', sa.Text(), nullable=True),
    sa.Column('is_voice_profile_created', sa.Boolean(), nullable=True),
    sa.Column('is_consent_required', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_index(op.f('ix_personas_target_id'), 'personas', ['target_id'], unique=True)
    op.create_table('storybooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_path', sa.String(length=512), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storybooks_id'), 'storybooks', ['id'], unique=False)
    op.create_index(op.f('ix_storybooks_target_id'), 'storybooks', ['target_id'], unique=False)
    op.create_index(op.f('ix_storybooks_user_id'), 'storybooks', ['user_id'], unique=False)
    op.create_table('target_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'AUDIO', name='mediatype'), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_media_id'), 'target_media', ['id'], unique=False)
    op.create_index(op.f('ix_target_media_target_id'), 'target_media', ['target_id'], unique=False)
    op.create_table('group_storybooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('storybook_id', sa.Integer(), nullable=False),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['memory_groups.id'], ),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['storybook_id'], ['storybooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_storybooks_group_id'), 'group_storybooks', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_storybooks_id'), 'group_storybooks', ['id'], unique=False)
    op.create_index(op.f('ix_group_storybooks_storybook_id'), 'group_storybooks', ['storybook_id'], unique=False)
    op.create_table('persona_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_chats_id'), 'persona_chats', ['id'], unique=False)
    op.create_index(op.f('ix_persona_chats_persona_id'), 'persona_chats', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_chats_user_id'), 'persona_chats', ['user_id'], unique=False)
    op.create_table('persona_voice_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('reference_voice_file_path', sa.String(length=512), nullable=True),
    sa.Column('reference_voice_mime_type', sa.String(length=100), nullable=True),
    sa.Column('reference_voice_duration', sa.Integer(), nullable=True),
    sa.Column('voice_provider', sa.String(length=100), nullable=True),
    sa.Column('voice_id', sa.String(length=255), nullable=True),
    sa.Column('voice_name', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_voice_profiles_id'), 'persona_voice_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_persona_voice_profiles_persona_id'), 'persona_voice_profiles', ['persona_id'], unique=True)
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storybook_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'COMMENT', 'EDIT', name='sharepermission'), nullable=False),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['storybook_id'], ['storybooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_id'), 'share_links', ['id'], unique=False)
    op.create_index(op.f('ix_share_links_share_token'), 'share_links', ['share_token'], unique=True)
    op.create_index(op.f('ix_share_links_storybook_id'), 'share_links', ['storybook_id'], unique=False)
    op.create_table('story_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storybook_id', sa.Integer(), nullable=False),
    sa.Column('chapter_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storybook_id'], ['storybooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_chapters_id'), 'story_chapters', ['id'], unique=False)
    op.create_index(op.f('ix_story_chapters_storybook_id'), 'story_chapters', ['storybook_id'], unique=False)
    op.create_table('persona_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('USER', 'PERSONA', 'SYSTEM', name='sendertype'), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'AUDIO', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=512), nullable=True),
    sa.Column('audio_mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['persona_chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_messages_chat_id'), 'persona_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_persona_messages_id'), 'persona_messages', ['id'], unique=False)
    op.create_table('story_voice_narrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storybook_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('narration_file_path', sa.String(length=512), nullable=False),
    sa.Column('narration_mime_type', sa.String(length=100), nullable=False),
    sa.Column('narration_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('narration_type', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['story_chapters.id'], ),
    sa.ForeignKeyConstraint(['storybook_id'], ['storybooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_voice_narrations_chapter_id'), 'story_voice_narrations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_story_voice_narrations_id'), 'story_voice_narrations', ['id'], unique=False)
    op.create_index(op.f('ix_story_voice_narrations_storybook_id'), 'story_voice_narrations', ['storybook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_voice_narrations_storybook_id'), table_name='story_voice_narrations')
    op.drop_index(op.f('ix_story_voice_narrations_id'), table_name='story_voice_narrations')
    op.drop_index(op.f('ix_story_voice_narrations_chapter_id'), table_name='story_voice_narrations')
    op.drop_table('story_voice_narrations')
    op.drop_index(op.f('ix_persona_messages_id'), table_name='persona_messages')
    op.drop_index(op.f('ix_persona_messages_chat_id'), table_name='persona_messages')
    op.drop_table('persona_messages')
    op.drop_index(op.f('ix_story_chapters_storybook_id'), table_name='story_chapters')
    op.drop_index(op.f('ix_story_chapters_id'), table_name='story_chapters')
    op.drop_table('story_chapters')
    op.drop_index(op.f('ix_share_links_storybook_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_share_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_persona_voice_profiles_persona_id'), table_name='persona_voice_profiles')
    op.drop_index(op.f('ix_persona_voice_profiles_id'), table_name='persona_voice_profiles')
    op.drop_table('persona_voice_profiles')
    op.drop_index(op.f('ix_persona_chats_user_id'), table_name='persona_chats')
    op.drop_index(op.f('ix_persona_chats_persona_id'), table_name='persona_chats')
    op.drop_index(op.f('ix_persona_chats_id'), table_name='persona_chats')
    op.drop_table('persona_chats')
    op.drop_index(op.f('ix_group_storybooks_storybook_id'), table_name='group_storybooks')
    op.drop_index(op.f('ix_group_storybooks_id'), table_name='group_storybooks')
    op.drop_index(op.f('ix_group_storybooks_group_id'), table_name='group_storybooks')
    op.drop_table('group_storybooks')
    op.drop_index(op.f('ix_target_media_target_id'), table_name='target_media')
    op.drop_index(op.f('ix_target_media_id'), table_name='target_media')
    op.drop_table('target_media')
    op.drop_index(op.f('ix_storybooks_user_id'), table_name='storybooks')
    op.drop_index(op.f('ix_storybooks_target_id'), table_name='storybooks')
    op.drop_index(op.f('ix_storybooks_id'), table_name='storybooks')
    op.drop_table('storybooks')
    op.drop_index(op.f('ix_personas_target_id'), table_name='personas')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_consent_logs_user_id'), table_name='consent_logs')
    op.drop_index(op.f('ix_consent_logs_target_id'), table_name='consent_logs')
    op.drop_index(op.f('ix_consent_logs_id'), table_name='consent_logs')
    op.drop_table('consent_logs')
    op.drop_index(op.f('ix_ai_interview_sessions_user_id'), table_name='ai_interview_sessions')
    op.drop_index(op.f('ix_ai_interview_sessions_target_id'), table_name='ai_interview_sessions')
    op.drop_index(op.f('ix_ai_interview_sessions_photo_memory_id'), table_name='ai_interview_sessions')
    op.drop_index(op.f('ix_ai_interview_sessions_id'), table_name='ai_interview_sessions')
    op.drop_table('ai_interview_sessions')
    op.drop_index(op.f('ix_targets_user_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_photo_memories_user_id'), table_name='photo_memories')
    op.drop_index(op.f('ix_photo_memories_id'), table_name='photo_memories')
    op.drop_table('photo_memories')
    op.drop_index(op.f('ix_memory_groups_id'), table_name='memory_groups')
    op.drop_index(op.f('ix_memory_groups_group_code'), table_name='memory_groups')
    op.drop_index(op.f('ix_memory_groups_creator_id'), table_name='memory_groups')
    op.drop_table('memory_groups')
    op.drop_index(op.f('ix_deletion_requests_user_id'), table_name='deletion_requests')
    op.drop_index(op.f('ix_deletion_requests_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

