"""add_audit_log_model_and_functionality

Revision ID: b607621bd6f3
Revises: ef56ab12cd34
Create Date: 2026-05-12 03:07:43.394509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b607621bd6f3'
down_revision = 'ef56ab12cd34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_verification_requests', 'verification_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('FAMILY_RELATION_CERTIFICATE', 'ID_CARD', 'SELF_DECLARATION', 'OTHER', name='verificationtype'),
               existing_nullable=False)
    op.alter_column('target_verification_requests', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('PENDING', 'NEED_MORE_INFO', 'APPROVED', 'REJECTED', 'EXPIRED', 'REVOKED', name='verificationstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_index('stored_filename', table_name='target_verification_requests')
    op.create_index(op.f('ix_target_verification_requests_id'), 'target_verification_requests', ['id'], unique=False)
    op.drop_column('target_verification_requests', 'stored_filename')
    op.drop_column('target_verification_requests', 'document_file_path')
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('USER', 'ADMIN', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='userrole'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
    op.add_column('target_verification_requests', sa.Column('document_file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=True))
    op.add_column('target_verification_requests', sa.Column('stored_filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_index(op.f('ix_target_verification_requests_id'), table_name='target_verification_requests')
    op.create_index('stored_filename', 'target_verification_requests', ['stored_filename'], unique=False)
    op.alter_column('target_verification_requests', 'status',
               existing_type=sa.Enum('PENDING', 'NEED_MORE_INFO', 'APPROVED', 'REJECTED', 'EXPIRED', 'REVOKED', name='verificationstatus'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('target_verification_requests', 'verification_type',
               existing_type=sa.Enum('FAMILY_RELATION_CERTIFICATE', 'ID_CARD', 'SELF_DECLARATION', 'OTHER', name='verificationtype'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)

    # Drop audit_logs table
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

