"""user auth refactor

Revision ID: be1ee3f427ea
Revises: 2e68f1557ac8
Create Date: 2026-05-09 01:40:17.691490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be1ee3f427ea'
down_revision = '2e68f1557ac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=False))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'username')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('users', sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###

