"""add_usage_limits_and_rate_limit_models

Revision ID: e46ce20a7937
Revises: b607621bd6f3
Create Date: 2026-05-12 03:19:20.074859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46ce20a7937'
down_revision = 'b607621bd6f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

